# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c212310b59706eddd5faa1490fb0afc8198c52bcd859069e9f92bd1685ca9a09295622532d0f0dca71c0e72204493fa03243e1202f05e025e63844f9ea9596

test:
  secret_key_base: b4714bde28da304e78329d12b422678317a0024f4e4a2668d353f5565da11eef03b914e65f9af857bd364e66ec31032d9cb936f6ec3a7a96153be57fc34f9f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
